### ISSUE TITLE
Per product taxonomy with product categories not working

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-call-for-price#20]
Describe the bug
Per product taxonomy with product categories not working.

To Reproduce
1. Call for the price set up : https://www.screencast.com/t/wLcnGlgNoZ
2. Product categories set up: https://www.screencast.com/t/tpv6foPNyA

Expected behavior
Products with these categories should appear with a Call for Price button on the categories page.

**Comment by Shasvat7** [comment]
@apeksha10 - I tried to replicate this issue with the latest v3.2.8 but I was not able to replicate this issue.
Here are the screenshots for the same:
Settings page: https://prnt.sc/11yzwwn
Shop page: https://prnt.sc/11z059l

So can you please re-check this issue?

**Comment by apeksha10** [comment]
With the latest git copy, I am not able to replicate the above issue

Call for Price label displayed fine on the product categories page.

Hence I closed this issue
