### ISSUE TITLE
Per product taxonomy with product tag not working.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-call-for-price#21]
Describe the bug
Per product taxonomy with product tag not working.

To Reproduce

Product Price: https://www.screencast.com/t/3LuawMlrd
Product tag: https://www.screencast.com/t/VNtlJPtZqzQO
Call for the price set up: https://www.screencast.com/t/1ZgHbUnNk
Products with these tags will not appear with a Call for Price button on the Shop page.
https://www.screencast.com/t/QmAj2dhBmmV3

Expected behavior
Products with these tags should appear with a Call for Price button on the Shop page.

**Comment by Shasvat7** [comment]
@apeksha10 - I tried to replicate this issue with the latest v3.2.8 but I was not able to replicate this issue.
Here are the screenshots for the same:
Settings page: https://prnt.sc/11yzwwn
Shop page: https://prnt.sc/11z059l

So can you please re-check this issue?

**Comment by apeksha10** [comment]
With the latest git copy, I am not able to replicate the above issue.

Per product taxonomy-->Product tag setting works fine.

Hence I have closed this issue.
