### ISSUE TITLE
Translation to WPML

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/woocommerce-call-for-price#22]
The client wants the text to be translated in a different languages. I have replicated the issue where the text is not getting translated.

Link: https://wordpress.org/support/topic/translation-into-wpml/

**Comment by Shasvat7** [comment]
With the latest git copy, this issue is not getting replicated and the CFP text is translated as per the strings set for the languages.
Here's the video of it: https://www.awesomescreenshot.com/video/5848055?key=89f93f6805113b1c1fe4b7b644a36f9b
hence, closing the issue.
